version: '3'
services:
  invitation-service-mysql:
    image: mysql:8.0.19
    platform: linux/amd64
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/db/logs:/var/log/mysql
      - ./docker/db//my.cnf:/etc/mysql/conf.d/my.cnf
    container_name: invitation-service-mysql
    env_file:
      - .env

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
      args:
        - GITHUB_TOKEN=$GITHUB_TOKEN
        - DATABASE_URL=mysql://root:pass@invitation-service-mysql:3306/invitation_service?schema=public
    depends_on:
      - invitation-service-mysql
    ports:
      - 50055:50055
    volumes:
      - ./src:/app/src

volumes:
  mysql-data:
