FROM node:16.18.0

WORKDIR /app

ENV NODE_ENV local

ARG GITHUB_TOKEN
ENV GITHUB_TOKEN $GITHUB_TOKEN
ARG DATABASE_URL
ENV DATABASE_URL $DATABASE_URL

COPY package.json ./
COPY yarn.lock ./
COPY .npmrc ./
RUN echo "DATABASE_URL=$DATABASE_URL" >> ./.env

COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY nest-cli.json ./
COPY prisma ./prisma

RUN yarn install

EXPOSE 50055

CMD [ "yarn", "run", "start:debug" ]
